import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer'
import { fmtPace } from '@/lib/utils'

interface Row {
  mile: number
  name: string
  area: string
  time: string
  isCheer: boolean
  isFinish: boolean
  hasPhotographer: boolean
}

interface Props {
  rows: Row[]
  startTime: string
  targetHours: number
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: '#1a2535' },
  header: { marginBottom: 20 },
  title: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#64748b', marginBottom: 2 },
  cheerNote: { fontSize: 9, color: '#D6246E', marginBottom: 16 },
  table: { width: '100%' },
  thead: { flexDirection: 'row', background: '#1a2535', borderRadius: 4, marginBottom: 2 },
  th: { padding: '6 8', fontFamily: 'Helvetica-Bold', color: 'white', fontSize: 9 },
  thMile: { width: '10%', textAlign: 'center' },
  thLandmark: { width: '40%' },
  thArea: { width: '20%' },
  thTime: { width: '15%', textAlign: 'center' },
  thNotes: { width: '15%' },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#f1f5f9', borderBottomStyle: 'solid', alignItems: 'center' },
  rowCheer: { backgroundColor: '#fff0f6' },
  rowFinish: { backgroundColor: '#e6f5f4' },
  td: { padding: '5 8', fontSize: 9 },
  tdMile: { width: '10%', textAlign: 'center' },
  tdLandmark: { width: '40%' },
  tdArea: { width: '20%', color: '#64748b' },
  tdTime: { width: '15%', textAlign: 'center', fontFamily: 'Helvetica-Bold' },
  tdNotes: { width: '15%', fontSize: 8 },
  boldCheer: { fontFamily: 'Helvetica-Bold', color: '#D6246E' },
  boldFinish: { fontFamily: 'Helvetica-Bold', color: '#00857A' },
  footer: { position: 'absolute', bottom: 24, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#94a3b8' },
})

function fmtTarget(h: number): string {
  const hrs = Math.floor(h)
  const mins = Math.round((h - hrs) * 60)
  return mins === 0 ? `${hrs}h 00m` : `${hrs}h ${String(mins).padStart(2, '0')}m`
}

function PlannerDocument({ rows, startTime, targetHours }: Props) {
  const minPerMile = (targetHours * 60) / 26.2
  const pace = fmtPace(minPerMile)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>London Marathon 2026 Race Plan</Text>
          <Text style={styles.subtitle}>
            Start: {startTime} · Target: {fmtTarget(targetHours)} · Pace: {pace}/mile
          </Text>
          <Text style={styles.cheerNote}>Asthma + Lung UK Team Breathe cheer points highlighted</Text>
        </View>

        <View style={styles.table}>
          <View style={styles.thead}>
            <Text style={[styles.th, styles.thMile]}>Mile</Text>
            <Text style={[styles.th, styles.thLandmark]}>Landmark</Text>
            <Text style={[styles.th, styles.thArea]}>Area</Text>
            <Text style={[styles.th, styles.thTime]}>Est. Arrival</Text>
            <Text style={[styles.th, styles.thNotes]}>Notes</Text>
          </View>

          {rows.map((row) => {
            const rowStyle = row.isFinish ? styles.rowFinish : row.isCheer ? styles.rowCheer : undefined
            const textStyle = row.isFinish ? styles.boldFinish : row.isCheer ? styles.boldCheer : undefined
            const notes = row.isCheer
              ? row.hasPhotographer
                ? '🫁 Team Breathe · 📸 Photographer'
                : '🫁 Team Breathe Cheer Point'
              : ''

            return (
              <View key={row.mile} style={[styles.row, rowStyle ?? {}]}>
                <Text style={[styles.td, styles.tdMile, textStyle ?? {}]}>{row.mile}</Text>
                <Text style={[styles.td, styles.tdLandmark, textStyle ?? {}]}>{row.name}</Text>
                <Text style={[styles.td, styles.tdArea]}>{row.area}</Text>
                <Text style={[styles.td, styles.tdTime, textStyle ?? {}]}>{row.time}</Text>
                <Text style={[styles.td, styles.tdNotes, textStyle ?? {}]}>{notes}</Text>
              </View>
            )
          })}
        </View>

        <Text style={styles.footer}>
          Generated by London Marathon Race Planner · 26 April 2026
        </Text>
      </Page>
    </Document>
  )
}

const btnStyle: React.CSSProperties = {
  display: 'inline-block',
  background: '#D6246E',
  color: 'white',
  borderRadius: 10,
  padding: '14px 32px',
  fontSize: '1rem',
  fontWeight: 700,
  textDecoration: 'none',
  fontFamily: 'inherit',
}

export default function PlannerPdfButton({ rows, startTime, targetHours }: Props) {
  const filename = `marathon-race-plan-${startTime.replace(':', '')}.pdf`
  return (
    <PDFDownloadLink
      document={<PlannerDocument rows={rows} startTime={startTime} targetHours={targetHours} />}
      fileName={filename}
      style={btnStyle}
    >
      {({ loading }) => (loading ? 'Building PDF…' : 'Download PDF')}
    </PDFDownloadLink>
  )
}
